//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_default : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.default_Pose;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonLeftHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonLeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton SkeletonRightHand
        {
            get
            {
                return SteamVR_Actions.default_SkeletonRightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean HeadsetOnHead
        {
            get
            {
                return SteamVR_Actions.default_HeadsetOnHead;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnLeft
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean SnapTurnRight
        {
            get
            {
                return SteamVR_Actions.default_SnapTurnRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean LaserLeft
        {
            get
            {
                return SteamVR_Actions.default_LaserLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean LaserRight
        {
            get
            {
                return SteamVR_Actions.default_LaserRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabLeft
        {
            get
            {
                return SteamVR_Actions.default_GrabLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean GrabRight
        {
            get
            {
                return SteamVR_Actions.default_GrabRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean GripLeft
        {
            get
            {
                return SteamVR_Actions.default_GripLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean GripRight
        {
            get
            {
                return SteamVR_Actions.default_GripRight;
            }
        }
        
        public virtual SteamVR_Action_Boolean TeleportLeft
        {
            get
            {
                return SteamVR_Actions.default_TeleportLeft;
            }
        }
        
        public virtual SteamVR_Action_Boolean TeleportRight
        {
            get
            {
                return SteamVR_Actions.default_TeleportRight;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.default_Haptic;
            }
        }
    }
}
